In [1]:
[1, 2, 3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [2]:
[1, 2, 3] * [4, 5, 6]

TypeError: can't multiply sequence by non-int of type 'list'

# Numerical Python (Numpy)

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
a*3

array([3, 6, 9])

# Math Functions

In [14]:
np.sum(a)

6

In [15]:
np.mean(a)

2.0

In [16]:
np.std(a)

0.816496580927726

In [17]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

# Arange, Linspace Logspace

In [18]:
np.arange(0,5,1.5)

array([0. , 1.5, 3. , 4.5])

In [19]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.logspace(-3,3,7)

array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])

# Random

In [21]:
np.random.rand(3,2)

array([[0.03680901, 0.30152658],
       [0.81396506, 0.52280019],
       [0.77315685, 0.01436909]])

# Controlled Randomness

In [22]:
state = np.random.RandomState(42)
state.rand(3)

array([0.37454012, 0.95071431, 0.73199394])